def custom_data():
    arr = [
        "FHHHHHFFFFFFFFFFHHHF",
        "FFFFFFFFHHFFFFFFFFFF",
        "FFFFFFFFHFFFFFFFFFFF",
        "SFFFFFFFHFFFFFFFFFFF",
        "FFFFFFFFHFFFFFFFFFFF",
        "FFFFFFFFHFFFFFFFFFFF",
        "FFFFFFFFHFFFFFFHHHFF",
        "HHFFFFFFHFFFFFHFFFFF",
        "FFFFFFFFHHHHHHHHFFFF",
        "FFFFFFFFFFFFFFFFFFFF",
        "HHFFFFFHHFFFFFFFFFFF",
        "FFFFFFFHHFFFFFFFFFFG",
        "FFFFFHFFHFFFFFFFFFFF",
        "FFFFFHHHHHHHHHHFFFFF",
        "FFFFFFFFFFFFFFFFFFFF",
        "FFFFHHHHHHHHHHFFFFFF",
        "FFFFFHHHHHHHHHHHHHHF", 
        "FFFFFHFFFFFFFFFFFFFF",
        "FFFFFHFHHHFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFHHHH"

    ]
    return arr
